using UnityEngine;

namespace MapChanger.Input;

public abstract class KeyInputSource : AbstractInputSource
{
    public abstract KeyCode Key { get; }

    public override bool GetPressed()
    {
        return UnityEngine.Input.GetKeyDown(Key);
    }

    public override bool GetReleased()
    {
        return UnityEngine.Input.GetKeyUp(Key);
    }

    public override string GetBindingsText()
    {
        return ToChar(Key);
    }

    public static string ToChar(KeyCode keyCode)
    {
        return keyCode switch
        {
            KeyCode.Backspace => "⌫",
            KeyCode.Delete => "⌦",
            KeyCode.Tab => "⇥",
            KeyCode.Clear => "⌧",
            KeyCode.Return => "⏎",
            KeyCode.Pause => "⏸",
            KeyCode.Escape => "⎋",
            KeyCode.Space => "␣",
            KeyCode.Keypad0 => "0",
            KeyCode.Keypad1 => "1",
            KeyCode.Keypad2 => "2",
            KeyCode.Keypad3 => "3",
            KeyCode.Keypad4 => "4",
            KeyCode.Keypad5 => "5",
            KeyCode.Keypad6 => "6",
            KeyCode.Keypad7 => "7",
            KeyCode.Keypad8 => "8",
            KeyCode.Keypad9 => "9",
            KeyCode.KeypadPeriod => ".",
            KeyCode.KeypadDivide => "/",
            KeyCode.KeypadMultiply => "✕",
            KeyCode.KeypadMinus => "-",
            KeyCode.KeypadPlus => "+",
            KeyCode.KeypadEnter => "⏎",
            KeyCode.KeypadEquals => "=",
            KeyCode.UpArrow => "↑",
            KeyCode.DownArrow => "↓",
            KeyCode.RightArrow => "→",
            KeyCode.LeftArrow => "←",
            KeyCode.Insert => "⎀",
            KeyCode.Home => "⇱",
            KeyCode.End => "⇲",
            KeyCode.PageUp => "⇞",
            KeyCode.PageDown => "⇟",
            KeyCode.F1 => "F1",
            KeyCode.F2 => "F2",
            KeyCode.F3 => "F3",
            KeyCode.F4 => "F4",
            KeyCode.F5 => "F5",
            KeyCode.F6 => "F6",
            KeyCode.F7 => "F7",
            KeyCode.F8 => "F8",
            KeyCode.F9 => "F9",
            KeyCode.F10 => "F10",
            KeyCode.F11 => "F11",
            KeyCode.F12 => "F12",
            KeyCode.F13 => "F13",
            KeyCode.F14 => "F14",
            KeyCode.F15 => "F15",
            KeyCode.Alpha0 => "0",
            KeyCode.Alpha1 => "1",
            KeyCode.Alpha2 => "2",
            KeyCode.Alpha3 => "3",
            KeyCode.Alpha4 => "4",
            KeyCode.Alpha5 => "5",
            KeyCode.Alpha6 => "6",
            KeyCode.Alpha7 => "7",
            KeyCode.Alpha8 => "8",
            KeyCode.Alpha9 => "9",
            KeyCode.Exclaim => "!",
            KeyCode.DoubleQuote => "\"",
            KeyCode.Hash => "#",
            KeyCode.Dollar => "$",
            KeyCode.Percent => "%",
            KeyCode.Ampersand => "&",
            KeyCode.Quote => "'",
            KeyCode.LeftParen => "(",
            KeyCode.RightParen => ")",
            KeyCode.Asterisk => "*",
            KeyCode.Plus => "+",
            KeyCode.Comma => ",",
            KeyCode.Minus => "-",
            KeyCode.Period => ".",
            KeyCode.Slash => "/",
            KeyCode.Colon => ":",
            KeyCode.Semicolon => ";",
            KeyCode.Less => "<",
            KeyCode.Equals => "=",
            KeyCode.Greater => ">",
            KeyCode.Question => "?",
            KeyCode.At => "@",
            KeyCode.LeftBracket => "[",
            KeyCode.Backslash => "\\",
            KeyCode.RightBracket => "]",
            KeyCode.Caret => "^",
            KeyCode.Underscore => "_",
            KeyCode.BackQuote => "`",
            KeyCode.A => "A",
            KeyCode.B => "B",
            KeyCode.C => "C",
            KeyCode.D => "D",
            KeyCode.E => "E",
            KeyCode.F => "F",
            KeyCode.G => "G",
            KeyCode.H => "H",
            KeyCode.I => "I",
            KeyCode.J => "J",
            KeyCode.K => "K",
            KeyCode.L => "L",
            KeyCode.M => "M",
            KeyCode.N => "N",
            KeyCode.O => "O",
            KeyCode.P => "P",
            KeyCode.Q => "Q",
            KeyCode.R => "R",
            KeyCode.S => "S",
            KeyCode.T => "T",
            KeyCode.U => "U",
            KeyCode.V => "V",
            KeyCode.W => "W",
            KeyCode.X => "X",
            KeyCode.Y => "Y",
            KeyCode.Z => "Z",
            KeyCode.LeftCurlyBracket => "{",
            KeyCode.Pipe => "|",
            KeyCode.RightCurlyBracket => "}",
            KeyCode.Tilde => "~",
            KeyCode.Numlock => "⇭",
            KeyCode.CapsLock => "⇪",
            KeyCode.ScrollLock => "⤓",
            KeyCode.RightShift => "⇧",
            KeyCode.LeftShift => "⇧",
            KeyCode.RightAlt => "Alt",
            KeyCode.LeftAlt => "Alt",
            KeyCode.LeftCommand => "⌘",
            KeyCode.LeftWindows => "⊞",
            KeyCode.RightCommand => "⌘",
            KeyCode.RightWindows => "⊞",
            _ => string.Empty,
        };
    }
}
